'use server';

import { callOpenRouter, ComplianceSchema, type ComplianceData } from '@/lib/ai-client';
import { checkRateLimit } from '@/lib/rate-limit';
import { checkBotScore } from '@/lib/bot-protection';
import { headers } from 'next/headers';
import { createClient } from '@/lib/server';

export async function generateComplianceReport(rawAnswers: any) {
  try {
    // ── 0a. Bot Protection ────────────────────────────────────────────────
    const botCheck = await checkBotScore();
    if (botCheck.isBot) {
      return { success: false, error: 'Access denied: automated request detected.' };
    }

    // ── 0b. IP Rate Limiting (5 reports per hour) ─────────────────────────
    const headersList = await headers();
    const forwardedFor = headersList.get('x-forwarded-for');
    const ip = forwardedFor ? forwardedFor.split(',')[0].trim() : 'localhost';

    const limitStatus = await checkRateLimit(ip);
    if (!limitStatus.success) {
      return {
        success: false,
        error: 'Security limit reached: You can generate up to 5 reports per hour. Please try again shortly, or upgrade to PRO for unlimited access.',
      };
    }

    // ── 0c. One-Time Trial Check (for unsigned users) ───────────────────────
    const supabase = await createClient();
    const { data: { user } } = await supabase.auth.getUser();

    if (!user) {
      const { data: existingTrial } = await supabase
        .from('compliance_reports')
        .select('id')
        .eq('ip_address', ip)
        .is('user_id', null)
        .maybeSingle();

      if (existingTrial) {
        return {
          success: false,
          error: 'Trial limit reached: You have already generated one free report from this IP. Please sign in to generate more or access your dashboard.',
        };
      }
    }


    // ── 1. Input Validation (Zod) ─────────────────────────────────────────
    const result = ComplianceSchema.safeParse(rawAnswers);
    if (!result.success) {
      return { success: false, error: 'Invalid data provided. Please complete the questionnaire.' };
    }
    const answers = result.data;

    const industry      = answers.industry      || 'General Business';
    const dataTypes     = answers.data_types?.join(', ') || 'personal data';
    const companySize   = answers.company_size   || 'small';
    const jurisdiction  = answers.jurisdiction   || 'Global / International';
    const seed          = Math.random().toString(36).substring(2, 9);

    // ── 2. Unified High-Speed Generation (2026 Engine) ───────────────────
    const unifiedPrompt = `
You are a Senior Legal Partner at a premier global compliance firm. 
CLIENT PROFILE:
- Entity: ${industry} Firm
- Operational Scale: ${companySize}
- Data Sensitivity: ${dataTypes}
- Jurisdiction: ${jurisdiction}
[Session ID: ${seed}]

INSTRUCTIONS:
Generate a strictly professional, board-ready COMPLIANCE AUDIT BUNDLE. 
The tone must be authoritative, expert, and client-focused. 
Use clean Markdown. NO random JSON, NO technical keys, and NO conversational filler.

STRUCTURE (Follow this exactly):

# ComplianceShield AI — Professional Audit Bundle [v2026]
**INDUSTRY:** ${industry} | **REFERENCE:** CS-${seed.toUpperCase()}
**PREPARED:** ${new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}

---

## 📋 Table of Contents
| Section | Description | Page |
|:---|:---|:---:|
| **1. Executive Summary** | High-level risk overview | 01 |
| **2. Regulatory Landscape** | Applicable ${jurisdiction} statutes | 02 |
| **3. Data Processing Map** | Classification of ${dataTypes} | 03 |
| **4. Risk Assessment Matrix** | Identified threats and mitigations | 04 |
| **5. Operational Controls** | Security policies and safeguards | 06 |
| **6. Implementation Roadmap** | Step-by-step 2026 timeline | 08 |
| **7. Certification Checklist** | Internal audit verification points | 09 |

---

## 1. Executive Summary
[Write 150+ words of professional legal summary for a CEO/Board audience. Focus on the ${industry} sector]

## 2. Regulatory Landscape
[Detail the specific acts relevant to ${jurisdiction}, e.g., GDPR, CCPA, HIPAA. Use Article/Section numbers]

## 3. Data Processing Map
[Explain how ${dataTypes} should be handled, encrypted, and stored according to latest 2026 standards]

## 4. Risk Assessment Matrix
[Identify three primary risks for ${industry} firms and provided specific mitigation strategies]

## 5. Operational Controls
[Write the technical and organizational measures (TOMs) required for this firm size]

## 6. Implementation Roadmap
[Provide a clear, 6-month priority list for achieving full compliance]

## 7. Certification Checklist
[A checklist of internal verification points for the legal department]

---
*PROVISION: This document was generated by ComplianceShield AI on ${new Date().toISOString().split('T')[0]}. Reference: CS-${seed.toUpperCase()}. Certified by ComplianceShield AI Engine [v2026-X]. This report is provided for informational purposes only and should be reviewed by legal counsel.*
    `.trim();

    const finalReport = await callOpenRouter(unifiedPrompt, 'google/gemini-2.0-flash-exp:free', 3200); 

    if (!finalReport) throw new Error('AI Engine failed to produce a report.');

    // ── 3. Persist to Supabase ────────────────────────────────────────────
    const userAgent = headersList.get('user-agent') || 'Unknown';

    const { error: dbError } = await supabase.from('compliance_reports').insert([{
      report_content: finalReport,
      ip_address:     ip,
      user_agent:     userAgent,
      industry:       industry,
      user_id:        user?.id ?? null,
    }]);




    if (dbError) {
      // Log but don't fail — the report was generated successfully
      console.error('DB Insert Error (non-fatal):', JSON.stringify(dbError, null, 2));
    }

    return {
      success: true,
      data: finalReport,
      meta: {
        model:      'ComplianceShield AI Engine (2-Step)',
        reference:  `CS-${seed.toUpperCase()}`,
        industry,
        secure:     true,
      },
    };

  } catch (error: any) {
    console.error('Compliance Engine Error:', error);
    return {
      success: false,
      error: `Generation failed: ${error.message || 'Unexpected error. Please try again.'}`,
    };
  }
}
