'use server';

import { callOpenRouter, ComplianceSchema, type ComplianceData } from '@/lib/ai-client';
import { checkRateLimit } from '@/lib/rate-limit';
import { checkBotScore } from '@/lib/bot-protection';
import { headers } from 'next/headers';
import { createClient } from '@/lib/server';

export async function generateComplianceReport(rawAnswers: any) {
  try {
    // ── 0a. Bot Protection ────────────────────────────────────────────────
    const botCheck = await checkBotScore();
    if (botCheck.isBot) {
      return { success: false, error: 'Access denied: automated request detected.' };
    }

    // ── 0b. IP Rate Limiting (5 reports per hour) ─────────────────────────
    const headersList = await headers();
    const forwardedFor = headersList.get('x-forwarded-for');
    const ip = forwardedFor ? forwardedFor.split(',')[0].trim() : 'localhost';

    const limitStatus = await checkRateLimit(ip);
    if (!limitStatus.success) {
      return {
        success: false,
        error: 'Security limit reached: You can generate up to 5 reports per hour. Please try again shortly, or upgrade to PRO for unlimited access.',
      };
    }

    // ── 0c. One-Time Trial Check (for unsigned users) ───────────────────────
    const supabase = await createClient();
    const { data: { user } } = await supabase.auth.getUser();

    if (!user) {
      const { data: existingTrial } = await supabase
        .from('compliance_reports')
        .select('id')
        .eq('ip_address', ip)
        .is('user_id', null)
        .maybeSingle();

      if (existingTrial) {
        return {
          success: false,
          error: 'Trial limit reached: You have already generated one free report from this IP. Please sign in to generate more or access your dashboard.',
        };
      }
    }


    // ── 1. Input Validation (Zod) ─────────────────────────────────────────
    const result = ComplianceSchema.safeParse(rawAnswers);
    if (!result.success) {
      return { success: false, error: 'Invalid data provided. Please complete the questionnaire.' };
    }
    const answers = result.data;

    const industry      = answers.industry      || 'General Business';
    const dataTypes     = answers.data_types?.join(', ') || 'personal data';
    const companySize   = answers.company_size   || 'small';
    const jurisdiction  = answers.jurisdiction   || 'Global / International';
    const seed          = Math.random().toString(36).substring(2, 9);

    // ── 2. Unified High-Speed Generation (2026 Engine) ───────────────────
    const unifiedPrompt = `
You are a Senior Legal Partner at a world-class compliance firm. [Session: ${seed}]

Write a comprehensive, professional COMPLIANCE REPORT for this client:
- Industry: ${industry}
- Company Size: ${companySize} 
- Data Types: ${dataTypes}
- Jurisdiction: ${jurisdiction}
- Context: ${JSON.stringify(answers)}

FORMAT REQUIREMENTS (follow exactly):
# ComplianceShield AI — ${industry} Compliance Bundle
**Generated:** ${new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })} | **Reference:** CS-${seed.toUpperCase()}

---

## 📋 Table of Contents
| # | Section | Description |
|---|---------|-------------|
| 1 | Executive Summary | Overview of your compliance status |
| 2 | Regulatory Scope | Laws relevant to ${industry} |
| 3 | Data Framework | Classification of ${dataTypes} |
| 4 | Risk Matrix | Identified threats and mitigations |
| 5 | Security Controls | Policy requirements and technical safeguards |
| 6 | Timeline | Step-by-step implementation roadmap |
| 7 | Audit Checklist | Verification points for compliance |

---

Now write each section in full detail (minimum 150 words per section). Use markdown headers, bullet points, and tables. Be specific to ${industry}. Include real regulation references (GDPR Articles, HIPAA §§, CCPA).

End with:
---
*This document was generated by ComplianceShield AI on ${new Date().toISOString().split('T')[0]}. Reference: CS-${seed.toUpperCase()}. Certified by ComplianceShield AI Engine [v2026-X]. This report is provided for informational purposes.*
    `.trim();

    console.log(`[SPEED-ENGINE] Starting single-pass generation...`);
    const finalReport = await callOpenRouter(unifiedPrompt, 'google/gemini-2.0-flash-exp:free', 4000);
    
    if (!finalReport) throw new Error('AI Engine failed to produce a report.');

    // ── 3. Persist to Supabase ────────────────────────────────────────────
    const userAgent = headersList.get('user-agent') || 'Unknown';

    const { error: dbError } = await supabase.from('compliance_reports').insert([{
      report_content: finalReport,
      ip_address:     ip,
      user_agent:     userAgent,
      industry:       industry,
      user_id:        user?.id ?? null,
    }]);



    if (dbError) {
      // Log but don't fail — the report was generated successfully
      console.error('DB Insert Error (non-fatal):', JSON.stringify(dbError, null, 2));
    }

    return {
      success: true,
      data: finalReport,
      meta: {
        model:      'ComplianceShield AI Engine (2-Step)',
        reference:  `CS-${seed.toUpperCase()}`,
        industry,
        secure:     true,
      },
    };

  } catch (error: any) {
    console.error('Compliance Engine Error:', error);
    return {
      success: false,
      error: `Generation failed: ${error.message || 'Unexpected error. Please try again.'}`,
    };
  }
}
