/**
 * OPENROUTER SECURITY CLIENT
 * [ARCHITECT NOTE]: Using x-title and http-referer allows us to 
 * professionalize our API footprint, preventing rate limits and 
 * showcasing the "ComplianceShield" brand to AI providers.
 */

import { z } from 'zod';

// Security Schema for Buyer Impression
// Updated to accept dynamic questions generated by the wizard
export const ComplianceSchema = z.any();

export type ComplianceData = z.infer<typeof ComplianceSchema>;

const FALLBACK_MODELS = [
  "google/gemini-2.0-flash-exp:free", // Highest daily limit (Stable)
  "google/gemini-flash-1.5-8b:free",  // Secondary high-capacity fallback
  "qwen/qwen-2.5-72b-instruct:free",  // High-Logic fallback
  "mistralai/mistral-7b-instruct:free" // Final safety net
];



export async function callOpenRouter(prompt: string, model: string = "openrouter/free", maxTokens: number = 2000) {
  const apiKey = process.env.OPENROUTER_API_KEY;
  if (!apiKey) throw new Error("OPENROUTER_API_KEY is missing from your .env.local file.");

  const modelsToTry = [model, ...FALLBACK_MODELS.filter(m => m !== model)];
  let lastErrorSummary = "";

  for (const currentModel of modelsToTry) {
    try {
      console.log(`[AI-DIAGNOSTIC] Trying model: ${currentModel}`);
      
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), 15000); // 15s Hard Timeout

      const response = await fetch("https://openrouter.ai/api/v1/chat/completions", {
        method: "POST",
        signal: controller.signal,
        headers: {
          "Authorization": `Bearer ${apiKey}`,
          "HTTP-Referer": "https://project-eight-orpin-33.vercel.app", 
          "X-Title": "ComplianceShield AI",
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          model: currentModel,
          messages: [{ role: "user", content: prompt }],
          temperature: 0.7, // Higher creativity for unique questions
          max_tokens: maxTokens,
        }),
      });

      clearTimeout(timeoutId);

      if (response.ok) {
        const data = await response.json();
        if (data.choices?.[0]?.message?.content) {
          return data.choices[0].message.content;
        }
      }

      // ── SMART RETRY LOGIC for FREE TIER ────────────────────────────────
      // If we hit a 429 (Rate Limit), we wait 2 seconds for a "Cooldown" 
      // before trying the next model. This often bypasses meta-limiters.
      if (response.status === 429) {
        console.warn(`[AI-COOLDOWN] Rate limit hit on ${currentModel}. Waiting 2s for bypass...`);
        await new Promise(resolve => setTimeout(resolve, 2000));
      }



      const errorData = await response.json().catch(() => ({}));
      const errorMsg = errorData.error?.message || response.statusText;
      console.warn(`[AI-DIAGNOSTIC] ${currentModel} failed (${response.status}): ${errorMsg}`);
      lastErrorSummary = `Detailed Reason: "${errorMsg}" (on model: ${currentModel})`;
      
    } catch (err: any) {
      console.warn(`[AI-DIAGNOSTIC] Connection error for ${currentModel}:`, err.message);
      lastErrorSummary = `Connection Error: ${err.message}`;
    }
  }

  throw new Error(`AI GENERATION FAILED after trying ${modelsToTry.length} models. \n\n${lastErrorSummary}\n\nTIP: If you see "Rate Limit Exceeded", wait 24 hours or add $5 balance to your OpenRouter account to unlock higher limits.`);
}


